# Generated by Django 6.0.4 on 2026-04-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wallet_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_expenses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_expenses',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
