# Generated by Django 6.0.4 on 2026-04-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_expenses_description_alter_add_expenses_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_expenses',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
