# Generated by Django 6.0.4 on 2026-04-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_add_expenses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='add_expenses',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='add_expenses',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
