# Generated by Django 6.0.4 on 2026-04-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
