# Generated by Django 6.0.4 on 2026-04-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='tasks',
        ),
    ]
